import type {
  AdaptiveQuizTurn,
  AdaptiveReviewTask,
  AnalysisBatch,
  AnalysisQueueItem,
  DecisionBlock,
  DecisionBlockFeedback,
  DelayedVerification,
  FeedbackInterpretation,
  ReviewCoachFormalSnapshot,
  SessionBlueprint,
  TaskOutcomeEvent,
} from "./domain";
import { EMPTY_REVIEW_COACH_FORMAL_SNAPSHOT } from "./domain";

export const coachTestStamp = "2026-09-04T08:00:00.000Z";

export const coachTestBlock: DecisionBlock = {
  id: "decision-block-1",
  recordId: "record-1",
  contentVersion: 1,
  position: 0,
  contentUpdatedAt: coachTestStamp,
  createdAt: coachTestStamp,
  updatedAt: coachTestStamp,
};

export const coachTestFeedback: DecisionBlockFeedback = {
  id: "feedback-1",
  decisionBlockId: coachTestBlock.id,
  recordId: coachTestBlock.recordId,
  contentVersion: 1,
  comment: "I confuse queue insertion and visited marking.",
  includeInAnalysis: true,
  source: "review",
  occurredAt: coachTestStamp,
  idempotencyKey: "feedback-operation-1",
  createdAt: coachTestStamp,
  updatedAt: coachTestStamp,
};

export const coachTestInterpretation: FeedbackInterpretation = {
  id: "interpretation-1",
  feedbackId: coachTestFeedback.id,
  decisionBlockId: coachTestBlock.id,
  contentVersion: 1,
  status: "succeeded",
  actionability: "needs_training",
  difficultyType: "procedure",
  stuckAt: "visited marking",
  userHypothesis: null,
  preferredPractice: "variation",
  missingInformation: [],
  confidence: 0.8,
  promptTokens: 120,
  completionTokens: 30,
  totalTokens: 150,
  requestId: "request-1",
  attemptCount: 1,
  aiGenerated: true,
  model: "fast-model",
  provider: "test",
  promptVersion: "feedback-interpretation-v1",
  policyVersion: "review-coach-policy-v1",
  schemaVersion: 1,
  createdAt: coachTestStamp,
  updatedAt: coachTestStamp,
};

export const coachTestQueueItem: AnalysisQueueItem = {
  id: "queue-1",
  feedbackId: coachTestFeedback.id,
  decisionBlockId: coachTestBlock.id,
  recordId: coachTestBlock.recordId,
  contentVersion: 1,
  status: "consumed",
  eligibilityReason: "user-feedback",
  batchId: "batch-1",
  consumedAt: coachTestStamp,
  createdAt: coachTestStamp,
  updatedAt: coachTestStamp,
};

const analysisRef = {
  queueItemId: coachTestQueueItem.id,
  feedbackId: coachTestFeedback.id,
  interpretationId: coachTestInterpretation.id,
  decisionBlockId: coachTestBlock.id,
  recordId: coachTestBlock.recordId,
  contentVersion: 1,
};

export const coachTestBatch: AnalysisBatch = {
  id: "batch-1",
  status: "succeeded",
  inputRefs: [analysisRef],
  subBatches: [{ id: "sub-batch-1", inputRefs: [analysisRef], status: "succeeded" }],
  requestedAt: coachTestStamp,
  completedAt: coachTestStamp,
  finalSummary: "Practice the order of BFS operations.",
  provider: "test",
  model: "deep-model",
  promptVersion: "session-blueprint-v1",
  policyVersion: "review-coach-policy-v1",
  schemaVersion: 1,
  inputFingerprint: "input-1",
  idempotencyKey: "batch-operation-1",
  createdAt: coachTestStamp,
  updatedAt: coachTestStamp,
};

export const coachTestBlueprint: SessionBlueprint = {
  id: "blueprint-1",
  batchId: coachTestBatch.id,
  decisionBlockId: coachTestBlock.id,
  recordId: coachTestBlock.recordId,
  contentVersion: 1,
  status: "accepted",
  supportingDecisionBlockIds: [],
  feedbackIds: [coachTestFeedback.id],
  interpretationIds: [coachTestInterpretation.id],
  problemHypothesis: "Operation order is not stable.",
  hypothesisConfidence: 0.8,
  objective: "Explain and apply the correct BFS order.",
  completionCriteria: ["Marks a node before duplicate enqueue"],
  initialPracticeType: "variation",
  initialDifficulty: 2,
  expectedKeyPoints: ["mark before enqueue"],
  branches: [
    { when: "correct", nextStrategy: "finish" },
    { when: "partial", nextStrategy: "hint" },
    { when: "incorrect", nextStrategy: "explain" },
    { when: "skipped", nextStrategy: "prerequisite-check" },
  ],
  allowedStrategies: ["finish", "hint", "explain", "prerequisite-check"],
  forbiddenScope: ["unrelated graph algorithms"],
  evidence: [{
    decisionBlockId: coachTestBlock.id,
    recordId: coachTestBlock.recordId,
    contentVersion: 1,
    excerptHash: "excerpt-1",
    purpose: "source",
  }],
  maxTurns: 4,
  maxRetriesPerTurn: 1,
  maxEstimatedTokens: 4000,
  provider: "test",
  model: "deep-model",
  promptVersion: "session-blueprint-v1",
  policyVersion: "review-coach-policy-v1",
  schemaVersion: 1,
  idempotencyKey: "blueprint-operation-1",
  createdAt: coachTestStamp,
  updatedAt: coachTestStamp,
};

export const coachTestTask: AdaptiveReviewTask = {
  id: "task-1",
  blueprintId: coachTestBlueprint.id,
  decisionBlockId: coachTestBlock.id,
  recordId: coachTestBlock.recordId,
  contentVersion: 1,
  status: "completed",
  priorityTier: "first-difficulty",
  queuedAt: coachTestStamp,
  startedAt: coachTestStamp,
  endedAt: coachTestStamp,
  idempotencyKey: "task-operation-1",
  createdAt: coachTestStamp,
  updatedAt: coachTestStamp,
};

export const coachTestTurn: AdaptiveQuizTurn = {
  id: "turn-1",
  taskId: coachTestTask.id,
  decisionBlockId: coachTestBlock.id,
  recordId: coachTestBlock.recordId,
  contentVersion: 1,
  sequence: 1,
  status: "answered",
  practiceType: "variation",
  question: "When should a BFS node be marked visited?",
  displayedAt: coachTestStamp,
  sourceEvidence: coachTestBlueprint.evidence,
  answerCriteria: ["before enqueue"],
  hintsUsed: [],
  answerText: "Before enqueueing it.",
  answeredAt: coachTestStamp,
  assessment: "correct",
  assessmentRationale: "Matches the criterion.",
  qualityChecked: true,
  qualityModel: "fast-model",
  generationModel: "fast-model",
  promptVersion: "quiz-turn-v1",
  policyVersion: "review-coach-policy-v1",
  idempotencyKey: "turn-operation-1",
  createdAt: coachTestStamp,
  updatedAt: coachTestStamp,
};

export const coachTestAnswerOutcome: TaskOutcomeEvent = {
  id: "outcome-answer-1",
  taskId: coachTestTask.id,
  turnId: coachTestTurn.id,
  decisionBlockId: coachTestBlock.id,
  recordId: coachTestBlock.recordId,
  contentVersion: 1,
  kind: "answer-assessment",
  answerAssessment: "correct",
  occurredAt: coachTestStamp,
  idempotencyKey: "outcome-answer-operation-1",
  createdAt: coachTestStamp,
  updatedAt: coachTestStamp,
};

export const coachTestMasteredOutcome: TaskOutcomeEvent = {
  id: "outcome-mastered-1",
  taskId: coachTestTask.id,
  decisionBlockId: coachTestBlock.id,
  recordId: coachTestBlock.recordId,
  contentVersion: 1,
  kind: "self-assessment",
  subjectiveOutcome: "mastered",
  occurredAt: coachTestStamp,
  idempotencyKey: "outcome-mastered-operation-1",
  createdAt: coachTestStamp,
  updatedAt: coachTestStamp,
};

export const coachTestCompletedDisposition: TaskOutcomeEvent = {
  id: "outcome-completed-1",
  taskId: coachTestTask.id,
  decisionBlockId: coachTestBlock.id,
  recordId: coachTestBlock.recordId,
  contentVersion: 1,
  kind: "task-disposition",
  disposition: "completed",
  occurredAt: coachTestStamp,
  idempotencyKey: "outcome-completed-operation-1",
  createdAt: coachTestStamp,
  updatedAt: coachTestStamp,
};

export const coachTestVerification: DelayedVerification = {
  id: "verification-1",
  sourceOutcomeEventId: coachTestMasteredOutcome.id,
  decisionBlockId: coachTestBlock.id,
  recordId: coachTestBlock.recordId,
  contentVersion: 1,
  status: "completed",
  verificationEligibleAt: "2026-09-05T08:00:00.000Z",
  verificationDueAt: "2026-09-06T08:00:00.000Z",
  lastVerifiedAt: "2026-09-06T08:00:00.000Z",
  verificationOutcome: "retained",
  strategyVersion: "verification-v1",
  idempotencyKey: "verification-operation-1",
  createdAt: coachTestStamp,
  updatedAt: "2026-09-06T08:00:00.000Z",
};

export const completeCoachTestSnapshot = (): ReviewCoachFormalSnapshot => ({
  ...structuredClone(EMPTY_REVIEW_COACH_FORMAL_SNAPSHOT),
  decisionBlocks: [structuredClone(coachTestBlock)],
  decisionBlockFeedback: [structuredClone(coachTestFeedback)],
  feedbackInterpretations: [structuredClone(coachTestInterpretation)],
  analysisQueueItems: [structuredClone(coachTestQueueItem)],
  analysisBatches: [structuredClone(coachTestBatch)],
  sessionBlueprints: [structuredClone(coachTestBlueprint)],
  adaptiveReviewTasks: [structuredClone(coachTestTask)],
  adaptiveQuizTurns: [structuredClone(coachTestTurn)],
  taskOutcomeEvents: [structuredClone(coachTestAnswerOutcome), structuredClone(coachTestMasteredOutcome), structuredClone(coachTestCompletedDisposition)],
  delayedVerifications: [structuredClone(coachTestVerification)],
});
